#ifndef GTASA_H
#define GTASA_H

#include "CGame/C3DMarkers.h"
#include "CGame/CBone.h"
#include "CGame/CBulletTrace.h"
#include "CGame/CCamera.h"
#include "CGame/CEntity.h"
#include "CGame/CFxManager.h"
#include "CGame/CHAnimIFrame.h"
#include "CGame/CMenuManager.h"
#include "CGame/CModel.h"
#include "CGame/CObject.h"
#include "CGame/CPad.h"
#include "CGame/CParticleData.h"
#include "CGame/CPed.h"
#include "CGame/CPedIK.h"
#include "CGame/CPhysical.h"
#include "CGame/CPlaceable.h"
#include "CGame/CSurface.h"
#include "CGame/CTxdStore.h"
#include "CGame/CVehicle.h"
#include "CGame/CWeaponSlot.h"
#include "CGame/Pools.h"
#include "CGame/SCM.h"
#include "CGame/Transport/CAutomobile.h"
#include "CGame/Transport/CBike.h"
#include "CGame/Transport/CBmx.h"
#include "CGame/Transport/CBoat.h"
#include "CGame/Transport/CHeli.h"
#include "CGame/Transport/CMonsterTruck.h"
#include "CGame/Transport/CPlane.h"
#include "CGame/Transport/CQuad.h"
#include "CGame/Transport/CTrailer.h"
#include "CGame/Types.h"
#include "CGame/methods.h"

#endif // GTASA_H
